# Use Amazon Linux 2023 as the base image
FROM public.ecr.aws/amazonlinux/amazonlinux:2023

# Install necessary packages and development tools
RUN dnf update -y && \
    dnf install -y \
        python3 \
        python3-pip \
        gcc \
        gcc-c++ \
        java-17-amazon-corretto-devel \
        unzip \
        tar \
        gzip \
        make \
        cmake \
        git && \
    dnf clean all

# Install AWS Lambda Runtime Interface Client for Python
RUN pip3 install awslambdaric

# Set the working directory
WORKDIR /var/task

# Copy the function code and any dependencies
COPY app/ .

# Install Python dependencies if any
RUN pip3 install -r requirements.txt

# Set the entry point for the Lambda function
ENTRYPOINT [ "/usr/local/bin/python3", "-m", "awslambdaric" ]
CMD [ "lambda_function.handler" ]
